name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      worker: ${{ steps.filter.outputs.worker }}
      edge: ${{ steps.filter.outputs.edge }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            backend:
              - 'backend/**'
            worker:
              - 'worker/**'
            edge:
              - 'edge/**'
            frontend:
              - 'frontend/**'

  backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
      - name: Install, typecheck, test
        working-directory: backend
        run: |
          npm ci
          npx tsc -p tsconfig.json
          npm run -s test || true

  edge:
    needs: changes
    if: needs.changes.outputs.edge == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'edge/package-lock.json'
      - name: Install, typecheck, test
        working-directory: edge
        run: |
          npm ci
          npx tsc -p tsconfig.json
          npm run -s test || true

  frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Install, build
        working-directory: frontend
        run: |
          npm ci
          npm run -s build

