name: build-push-docr

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          build-args: |
            BUILD_SHA=${{ github.sha }}
          no-cache: true
          push: true
          tags: |
            registry.digitalocean.com/mm-motionmav-reg/backend:latest
            registry.digitalocean.com/mm-motionmav-reg/backend:sha-${{ github.sha }}

      - name: Build and push worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: registry.digitalocean.com/mm-motionmav-reg/worker:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: registry.digitalocean.com/mm-motionmav-reg/frontend:latest
